# --- Stage 1: Build the NestJS app ---
FROM node:18-alpine AS builder

WORKDIR /app

ARG DATABASE_URL
ARG MYSQL_USER_NAME
ARG MYSQL_USER_PASSWORD
ARG MYSQL_DATABASE
ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_USER
ARG EMAIL_PASS
ARG JWT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG FRONTEND_URL
ARG PORT

ENV DATABASE_URL=${DATABASE_URL}
ENV MYSQL_USER_NAME=${MYSQL_USER_NAME}
ENV MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_USER=${EMAIL_USER}
ENV EMAIL_PASS=${EMAIL_PASS}
ENV JWT_SECRET=${JWT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV PORT=${PORT}


# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build NestJS project
RUN npm run build


# --- Stage 2: Run the production app ---
FROM node:18-alpine AS runner

WORKDIR /app

# Copy only required files from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package*.json ./

EXPOSE 3000

# Command to run the app
CMD ["node", "dist/main.js"]
